version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - agify-network
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - agify-network
networks:
   agify-network: